USE AshkanPharmacyDb;
IF OBJECT_ID('dbo.AppMigrations') IS NULL CREATE TABLE dbo.AppMigrations(Id INT IDENTITY PRIMARY KEY,MigrationKey NVARCHAR(120) UNIQUE NOT NULL,AppliedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('dbo.Notifications') IS NULL CREATE TABLE dbo.Notifications(Id BIGINT IDENTITY PRIMARY KEY,Title NVARCHAR(180) NOT NULL,Body NVARCHAR(500),Severity NVARCHAR(30) NOT NULL DEFAULT 'Info',IsRead BIT NOT NULL DEFAULT 0,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('dbo.ExportJobs') IS NULL CREATE TABLE dbo.ExportJobs(Id BIGINT IDENTITY PRIMARY KEY,ExportType NVARCHAR(60) NOT NULL,RequestedBy NVARCHAR(100),CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),Status NVARCHAR(30) NOT NULL DEFAULT 'Completed');
