CREATE TABLE Medicines(Id INT IDENTITY PRIMARY KEY, NameFa NVARCHAR(200) NOT NULL, NameEn NVARCHAR(200), Barcode NVARCHAR(50) UNIQUE, Category NVARCHAR(100), Stock INT NOT NULL DEFAULT 0, MinStock INT NOT NULL DEFAULT 0, BuyPrice DECIMAL(18,2), SellPrice DECIMAL(18,2), Expiry DATE, Batch NVARCHAR(80), Manufacturer NVARCHAR(150));
CREATE TABLE Suppliers(Id INT IDENTITY PRIMARY KEY, Name NVARCHAR(200), Phone NVARCHAR(50), Address NVARCHAR(500));
CREATE TABLE Patients(Id INT IDENTITY PRIMARY KEY, FullName NVARCHAR(200), NationalCode NVARCHAR(20), Phone NVARCHAR(50));
CREATE TABLE Sales(Id INT IDENTITY PRIMARY KEY, CreatedAt DATETIME2 DEFAULT SYSDATETIME(), PatientId INT NULL, Total DECIMAL(18,2), Discount DECIMAL(18,2));
CREATE TABLE SaleItems(Id INT IDENTITY PRIMARY KEY, SaleId INT NOT NULL, MedicineId INT NOT NULL, Qty INT NOT NULL, UnitPrice DECIMAL(18,2));
