USE AshkanPharmacyDb;
IF OBJECT_ID('dbo.MedicineBatches') IS NULL CREATE TABLE dbo.MedicineBatches(Id INT IDENTITY PRIMARY KEY,MedicineId INT NOT NULL,BatchNo NVARCHAR(80) NOT NULL,ExpiryDate DATE NOT NULL,Quantity INT NOT NULL DEFAULT 0,PurchasePrice DECIMAL(18,2) NOT NULL DEFAULT 0);
IF OBJECT_ID('dbo.BackupHistory') IS NULL CREATE TABLE dbo.BackupHistory(Id INT IDENTITY PRIMARY KEY,FilePath NVARCHAR(500) NOT NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),CreatedBy NVARCHAR(100) NULL,Success BIT NOT NULL);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='IX_Batches_FEFO') CREATE INDEX IX_Batches_FEFO ON dbo.MedicineBatches(MedicineId,ExpiryDate) INCLUDE(Quantity);
