IF DB_ID('AshkanPharmacyDb') IS NULL CREATE DATABASE AshkanPharmacyDb;
GO
USE AshkanPharmacyDb;
GO
CREATE TABLE Users(Id INT IDENTITY PRIMARY KEY, Username NVARCHAR(80) NOT NULL UNIQUE, PasswordHash NVARCHAR(300) NOT NULL, DisplayNameFa NVARCHAR(150), DisplayNameEn NVARCHAR(150), Role NVARCHAR(30) NOT NULL, IsActive BIT NOT NULL DEFAULT 1, CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME());
CREATE TABLE Suppliers(Id INT IDENTITY PRIMARY KEY, Name NVARCHAR(180) NOT NULL, Phone NVARCHAR(40), Email NVARCHAR(150), Address NVARCHAR(500), IsActive BIT NOT NULL DEFAULT 1);
CREATE TABLE Patients(Id INT IDENTITY PRIMARY KEY, NationalCode NVARCHAR(20), FullName NVARCHAR(180) NOT NULL, Phone NVARCHAR(40), BirthDate DATE NULL, InsuranceProvider NVARCHAR(120), Notes NVARCHAR(1000));
CREATE TABLE Medicines(Id INT IDENTITY PRIMARY KEY, Barcode NVARCHAR(80) UNIQUE, NameFa NVARCHAR(180) NOT NULL, NameEn NVARCHAR(180), Category NVARCHAR(100), Manufacturer NVARCHAR(160), MinStock INT NOT NULL DEFAULT 0, IsActive BIT NOT NULL DEFAULT 1);
CREATE TABLE MedicineBatches(Id INT IDENTITY PRIMARY KEY, MedicineId INT NOT NULL REFERENCES Medicines(Id), BatchNo NVARCHAR(80), ExpiryDate DATE NULL, Quantity INT NOT NULL, BuyPrice DECIMAL(18,2) NOT NULL, SellPrice DECIMAL(18,2) NOT NULL);
CREATE TABLE Sales(Id BIGINT IDENTITY PRIMARY KEY, InvoiceNo NVARCHAR(50) NOT NULL UNIQUE, PatientId INT NULL REFERENCES Patients(Id), UserId INT NOT NULL REFERENCES Users(Id), SoldAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(), Total DECIMAL(18,2) NOT NULL);
CREATE TABLE SaleItems(Id BIGINT IDENTITY PRIMARY KEY, SaleId BIGINT NOT NULL REFERENCES Sales(Id), MedicineId INT NOT NULL REFERENCES Medicines(Id), BatchId INT NULL REFERENCES MedicineBatches(Id), Quantity INT NOT NULL, UnitPrice DECIMAL(18,2) NOT NULL);
CREATE TABLE AuditLogs(Id BIGINT IDENTITY PRIMARY KEY, UserId INT NULL REFERENCES Users(Id), ActionName NVARCHAR(100) NOT NULL, EntityName NVARCHAR(100), EntityId NVARCHAR(80), Details NVARCHAR(MAX), CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME());
GO
