USE AshkanPharmacyDb;
IF OBJECT_ID('dbo.HeldSales') IS NULL CREATE TABLE dbo.HeldSales(Id BIGINT IDENTITY PRIMARY KEY,Label NVARCHAR(120),Payload NVARCHAR(MAX),HeldAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),HeldBy NVARCHAR(100));
IF OBJECT_ID('dbo.Returns') IS NULL CREATE TABLE dbo.Returns(Id BIGINT IDENTITY PRIMARY KEY,SaleId INT NOT NULL,Reason NVARCHAR(300),Amount DECIMAL(18,2) NOT NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),CreatedBy NVARCHAR(100));
