USE AshkanPharmacyDb;
IF COL_LENGTH('dbo.Users','PasswordHash') IS NULL ALTER TABLE dbo.Users ADD PasswordHash NVARCHAR(200) NULL, PasswordSalt NVARCHAR(200) NULL, IsActive BIT NOT NULL CONSTRAINT DF_Users_IsActive DEFAULT(1);
IF OBJECT_ID('dbo.Prescriptions') IS NULL CREATE TABLE dbo.Prescriptions(Id INT IDENTITY PRIMARY KEY,PatientId INT NOT NULL,DoctorName NVARCHAR(160),PrescriptionNo NVARCHAR(80),Insurance NVARCHAR(100),CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),Notes NVARCHAR(500));
IF OBJECT_ID('dbo.Purchases') IS NULL CREATE TABLE dbo.Purchases(Id INT IDENTITY PRIMARY KEY,SupplierId INT NULL,InvoiceNo NVARCHAR(80),Total DECIMAL(18,2) NOT NULL DEFAULT 0,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('dbo.PurchaseItems') IS NULL CREATE TABLE dbo.PurchaseItems(Id INT IDENTITY PRIMARY KEY,PurchaseId INT NOT NULL,MedicineId INT NOT NULL,BatchNo NVARCHAR(80),ExpiryDate DATE NULL,Qty INT NOT NULL,UnitCost DECIMAL(18,2) NOT NULL);
IF OBJECT_ID('dbo.AppSettings') IS NULL CREATE TABLE dbo.AppSettings([Key] NVARCHAR(100) PRIMARY KEY,[Value] NVARCHAR(MAX) NULL);
CREATE INDEX IX_Medicines_Barcode ON dbo.Medicines(Barcode);
CREATE INDEX IX_Medicines_Expiry ON dbo.Medicines(ExpiryDate);
CREATE INDEX IX_Sales_CreatedAt ON dbo.Sales(CreatedAt);
