USE AshkanPharmacyDb;
IF OBJECT_ID('dbo.Payments') IS NULL CREATE TABLE dbo.Payments(Id BIGINT IDENTITY PRIMARY KEY,SaleId INT NOT NULL,Method NVARCHAR(30) NOT NULL,Subtotal DECIMAL(18,2) NOT NULL,Discount DECIMAL(18,2) NOT NULL DEFAULT 0,Tax DECIMAL(18,2) NOT NULL DEFAULT 0,Payable DECIMAL(18,2) NOT NULL,Reference NVARCHAR(100) NULL,PaidAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF COL_LENGTH('dbo.Sales','Discount') IS NULL ALTER TABLE dbo.Sales ADD Discount DECIMAL(18,2) NOT NULL CONSTRAINT DF_Sales_Discount DEFAULT 0;
IF COL_LENGTH('dbo.Sales','Tax') IS NULL ALTER TABLE dbo.Sales ADD Tax DECIMAL(18,2) NOT NULL CONSTRAINT DF_Sales_Tax DEFAULT 0;
