USE AshkanPharmacyDb;
IF OBJECT_ID('dbo.UserSessions') IS NULL CREATE TABLE dbo.UserSessions(Id BIGINT IDENTITY PRIMARY KEY,Username NVARCHAR(100) NOT NULL,RoleName NVARCHAR(80) NOT NULL,StartedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),EndedAt DATETIME2 NULL,MachineName NVARCHAR(120));
IF OBJECT_ID('dbo.SecurityEvents') IS NULL CREATE TABLE dbo.SecurityEvents(Id BIGINT IDENTITY PRIMARY KEY,Username NVARCHAR(100),EventType NVARCHAR(80) NOT NULL,Details NVARCHAR(500),OccurredAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
