USE AshkanPharmacyDb;
IF OBJECT_ID('dbo.RolePermissions') IS NULL CREATE TABLE dbo.RolePermissions(Id INT IDENTITY PRIMARY KEY,RoleName NVARCHAR(80) NOT NULL,PermissionKey NVARCHAR(100) NOT NULL,IsAllowed BIT NOT NULL DEFAULT 1,CONSTRAINT UQ_RolePermission UNIQUE(RoleName,PermissionKey));
IF OBJECT_ID('dbo.SystemHealthLog') IS NULL CREATE TABLE dbo.SystemHealthLog(Id BIGINT IDENTITY PRIMARY KEY,Component NVARCHAR(100) NOT NULL,Status NVARCHAR(30) NOT NULL,Details NVARCHAR(500),CheckedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
