using System;using System.Drawing;using System.Windows.Forms;using AshkanPharmacy.Core;using AshkanPharmacy.Models;
namespace AshkanPharmacy.Forms { public class PaymentForm:Form {
 NumericUpDown discount=new NumericUpDown(),tax=new NumericUpDown();ComboBox method=new ComboBox();Label due=new Label();decimal subtotal;public PaymentSummary Result{get;private set;}
 public PaymentForm(decimal amount){subtotal=amount;Text=Localization.Persian?"تسویه فروش":"Checkout";StartPosition=FormStartPosition.CenterParent;ClientSize=new Size(520,440);BackColor=Color.FromArgb(226,240,242);FormBorderStyle=FormBorderStyle.FixedDialog;MaximizeBox=false;MinimizeBox=false;Build();Calc();}
 void Build(){var hero=new GradientPanel{Left=20,Top=18,Width=480,Height=92,Color1=Theme.Teal,Color2=Theme.Indigo,Radius=20};Controls.Add(hero);hero.Controls.Add(new Label{Text=Localization.Persian?"تسویه و پرداخت":"Secure Checkout",Left=22,Top=17,Width=300,Height=32,Font=Theme.Font(17,FontStyle.Bold),ForeColor=Color.White});hero.Controls.Add(new Label{Text=subtotal.ToString("N0")+" IRR",Left=22,Top=52,Width=300,Height=24,ForeColor=Color.White});
 Label l1=new Label{Text=Localization.Persian?"تخفیف %":"Discount %",Left=30,Top=145,Width=120};discount.SetBounds(155,140,120,32);discount.Maximum=100;discount.ValueChanged+=(s,e)=>Calc();
 Label l2=new Label{Text=Localization.Persian?"مالیات %":"Tax %",Left=30,Top=195,Width=120};tax.SetBounds(155,190,120,32);tax.Maximum=100;tax.ValueChanged+=(s,e)=>Calc();
 Label l3=new Label{Text=Localization.Persian?"روش پرداخت":"Payment",Left=30,Top=245,Width=120};method.SetBounds(155,240,220,34);method.DropDownStyle=ComboBoxStyle.DropDownList;method.Items.AddRange(Enum.GetNames(typeof(PaymentMethod)));method.SelectedIndex=1;
 due.SetBounds(30,295,430,42);due.Font=Theme.Font(15,FontStyle.Bold);due.ForeColor=Theme.Navy;
 var ok=new AccentButton{Text=Localization.Persian?"تأیید پرداخت":"Confirm payment",Left=285,Top=360,Width=190,Height=48,BackColor=Theme.Teal,ForeColor=Color.White};ok.Click+=(s,e)=>{Result=new PaymentSummary{Subtotal=subtotal,Discount=PricingService.Discount(subtotal,discount.Value),Tax=PricingService.Tax(subtotal-PricingService.Discount(subtotal,discount.Value),tax.Value),Payable=PricingService.Payable(subtotal,discount.Value,tax.Value),Method=(PaymentMethod)Enum.Parse(typeof(PaymentMethod),method.SelectedItem.ToString())};DialogResult=DialogResult.OK;Close();};Controls.AddRange(new Control[]{l1,discount,l2,tax,l3,method,due,ok});}
 void Calc(){due.Text=(Localization.Persian?"مبلغ قابل پرداخت: ":"Payable: ")+PricingService.Payable(subtotal,discount.Value,tax.Value).ToString("N0")+" IRR";}
} }